### ISSUE TITLE
只能检测到自己最近打开的项目，无法检测到所在team某个project的项目

### ISSUE THREAD

**Issue by zhangsimon** [loo2k/figma-backup#2]
最近公司要迁移figma文件
搜到了这个工具 大喜过望
但试的时候发现只能检测到我的 recent里的文件列表

手动切换到team下某个project时
并没有刷新文件列表
不知道是不是因为文件太多了（大概160个）

还是说因为权限不够？
我只是成员（可以编辑文件），不是管理员？

**Comment by loo2k** [comment]
这个是另外一个 BUG 导致的问题，参考 #3 

目前已在 v0.2.1 版本中修复，检查一下更新或者重新安装脚本即可解决切换 Team 后没有刷新文件列表的问题。
